import os
import Main



# Test 1/9 - Accept CCA scenario, no failures
os.system("cls")
print()
print('#################################################################################')
print('Test 1/9 - Accept CCA scenario, no failures')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012345)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Pass', 'result': None}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 2/9 - Reject CCA scenario, Not signed failure
os.system("cls")
print()
print('#################################################################################')
print('Test 2/9 - Reject CCA scenario, Not signed failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012346)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'get_roi_for_element_no_expected()'. Error: No signature mark has been detected\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 3/9 - Reject CCA scenario, Alteration failure
os.system("cls")
print()
print('#################################################################################')
print('Test 3/9 - Reject CCA scenario, Alteration failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012347)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'check_for_alterations()'. Error: An alteration has been detected\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 4/9 - Reject CCA scenario, Wrong Name failure
os.system("cls")
print()
print('#################################################################################')
print('Test 4/9 - Reject CCA scenario, Wrong Name failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012348)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'Compare_Y_or_N(Name)'. Error: Values do not match\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 5/9 - Reject CCA scenario, Wrong Address failure
os.system("cls")
print()
print('#################################################################################')
print('Test 5/9 - Reject CCA scenario, Wrong Address failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012349)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'Compare_Y_or_N(Address Post Code)'. Error: Values do not match\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 6/9 - Reject CCA scenario, Wrong Account Name failure
os.system("cls")
print()
print('#################################################################################')
print('Test 6/9 - Reject CCA scenario, Wrong Account Name failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012350)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'Compare_Y_or_N(Account Name)'. Error: Values do not match\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 7/9 - Reject CCA scenario, Wrong Sort Code failure
os.system("cls")
print()
print('#################################################################################')
print('Test 7/9 - Reject CCA scenario, Wrong Sort Code failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012351)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'Compare_Y_or_N(Sort Code)'. Error: Values do not match\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 8/9 - Reject CCA scenario, Wrong Account Number failure
os.system("cls")
print()
print('#################################################################################')
print('Test 8/9 - Reject CCA scenario, Wrong Account Number failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012352)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'Compare_Y_or_N(Account Number)'. Error: Values do not match\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")

# Test 9/9 - Reject CCA scenario, Wrong Total Amount failure
os.system("cls")
print()
print('#################################################################################')
print('Test 9/9 - Reject CCA scenario, Wrong Total Amount failure')
print('#################################################################################')
print()
print('#####################################')
print('SCRIPT OUTPUT')
print('#####################################')
response = Main.query_db_for_record(987654321012353)
print()
print('#####################################')
print('OBSERVED RESPONSE')
print('#####################################')
print()
print(response)
print()
print('#####################################')
print('EXPECTED RESPONSE')
print('#####################################')
print()
print("{'response': 'Fail', 'result': \"Failed at 'Compare_Y_or_N(Total Amount)'. Error: Values do not match\"}")
print()
print('---------------------------------------------------------------------------------')
os.system("pause")
os.system("cls")
